name: censeo
description: Este aplicativo tem como objetivo ajudar os professores e alunos na melhora da qualidade das aulas.
publish_to: 'none'
version: 1.0.0+2


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http:
  google_fonts:
  shared_preferences:
  mask_text_input_formatter:
  rxdart:
  lottie:
  connectivity:
  bubble_bottom_bar:
    git: https://github.com/VitorHugoOli/bubble_bottom_bar.git
  badges:
  flutter_icons: ^1.1.0
  flutter_feather_icons:
  flutter_calendar_carousel:
  diacritic:
  logger:

dev_dependencies:
  flutter_test:
    sdk: flutter





flutter:
  uses-material-design: true

  assets:
    - assets/noConnection.json
    - assets/serverDown.json
    - assets/empty.json
    - assets/noAuth.json
    - assets/loader.json
    - assets/Avatar.png




  fonts:
    - family: Myriad Pro
      fonts:
        - asset: assets/fonts/MYRIADPRO-BOLD.OTF
    - family: ProfessorIcons
      fonts:
        - asset: assets/fonts/ProfessorIcons.ttf
  
  
  
  
  
  
  
  
