// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBczOtV4gLgwPWsc3gV2OSwIty_0eNELk0',
    appId: '1:378488913684:android:25746e4146af0ffd0ccc01',
    messagingSenderId: '378488913684',
    projectId: 'censeo-1ea51',
    storageBucket: 'censeo-1ea51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp1NQbn8nJVNrb11kdSVWlV7EeoNsl0lU',
    appId: '1:378488913684:ios:3361cc239dc7f4410ccc01',
    messagingSenderId: '378488913684',
    projectId: 'censeo-1ea51',
    storageBucket: 'censeo-1ea51.appspot.com',
    iosClientId: '378488913684-g56qj39abg7fqlgg2rrdsdnas01r07bg.apps.googleusercontent.com',
    iosBundleId: 'com.poc.censeo',
  );
}
